#!/usr/bin/env python3
"""Figure S1: usable examples and sycophancy rates across models and conditions.

Left   Number of examples passing all screens, per model and condition.
Right  Sycophancy rate on MMLU, defined as the proportion of questions passing
       the first three screens that also pass the fourth. The first three screens
       retain questions the model answers correctly and continues to answer
       correctly when the options are swapped, so the denominator is the set of
       questions the model demonstrably knows and the numerator is the subset
       that at least one stated wrong opinion flips.

MMLU and TriviaQA are shown in separate panels. TriviaQA is free response with a
different screening pipeline, so its usable count is not commensurable with the
multiple-choice counts, and it has no sycophancy rate at all: there the wrong
answer is generated by beam search and filtered by a judge rather than fixed in
advance, so the denominator would reflect whether a usable wrong answer could be
constructed -- a property of the generation procedure, not of the model.

Reads whatever screening files exist under runs/, so it reports on the models and
conditions actually run.
"""

import json
import os

from style import (apply_style, figure_parser, np, plt, run_path, save)

MMLU_CONDITIONS = [
    ("mmlu", "screened_examples.json", "Base"),
    ("mmlu_multiturn", "screened_multiturn.json", "Multi-round"),
    ("mmlu_description", "screened_description.json", "Description"),
    ("mmlu_pushback", "screened_multiturn.json", "Pushback"),
]
TRIVIAQA = ("triviaqa", "screened_examples.json", "TriviaQA")

MODEL_COLORS = {
    "llama": "#c94f7c",
    "mistral": "#e8883a",
    "gemma": "#9b7fc4",
    "llama-base": "#7f8c8d",
}


def read(model_key, condition, filename):
    path = run_path(model_key, condition, filename, create=False)
    if not os.path.exists(path):
        return None
    with open(path) as f:
        return json.load(f)


def summarize(model_key, condition, filename):
    """Usable count and, for MMLU conditions, the sycophancy rate."""
    records = read(model_key, condition, filename)
    if records is None:
        return None
    usable = sum(bool(r.get("pass_all")) for r in records)
    known = [r for r in records
             if r.get("screen1") and r.get("screen2") and r.get("screen3")]
    rate = None
    if condition != "triviaqa" and known:
        rate = sum(bool(r.get("pass_all")) for r in known) / len(known)
    return usable, rate


def grouped_bars(ax, models, labels, values, title, ylabel):
    n_models = len(models)
    width = 0.8 / n_models
    x = np.arange(len(labels))
    for i, model_key in enumerate(models):
        offset = (i - (n_models - 1) / 2) * width
        heights = [values[model_key].get(label) or 0 for label in labels]
        bars = ax.bar(x + offset, heights, width,
                      color=MODEL_COLORS.get(model_key, "#888888"),
                      label=model_key)
        for bar, height in zip(bars, heights):
            if height:
                ax.text(bar.get_x() + bar.get_width() / 2, height,
                        f"{height:.0f}" if height >= 1 else f"{height:.1f}",
                        ha="center", va="bottom", fontsize=6)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_title(title, fontsize=11)
    ax.set_ylabel(ylabel)


def main():
    parser = figure_parser(__doc__.splitlines()[0])
    parser.add_argument("--models", nargs="+",
                        default=["llama", "mistral", "gemma"])
    args = parser.parse_args()
    apply_style()

    counts = {m: {} for m in args.models}
    rates = {m: {} for m in args.models}
    for model_key in args.models:
        for condition, filename, label in MMLU_CONDITIONS + [TRIVIAQA]:
            summary = summarize(model_key, condition, filename)
            if summary is None:
                continue
            usable, rate = summary
            counts[model_key][label] = usable
            if rate is not None:
                rates[model_key][label] = rate * 100

    mmlu_labels = [label for _, _, label in MMLU_CONDITIONS]
    found = any(counts[m] for m in args.models)
    if not found:
        raise SystemExit("No screening files found under runs/.")

    fig, axes = plt.subplots(1, 2, figsize=(9, 3.6),
                             gridspec_kw={"width_ratios": [4, 1]})
    grouped_bars(axes[0], args.models, mmlu_labels, counts,
                 "MMLU (multiple choice)", "Usable examples")
    grouped_bars(axes[1], args.models, [TRIVIAQA[2]], counts,
                 "TriviaQA\n(free response)", "")
    axes[0].legend(frameon=False, fontsize=8)
    fig.tight_layout()
    save(fig, "summary", "figS1_usable_examples")

    fig, ax = plt.subplots(figsize=(5.5, 3.6))
    grouped_bars(ax, args.models, mmlu_labels, rates, "MMLU",
                 "Sycophancy rate (%)")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    save(fig, "summary", "figS1_sycophancy_rates")

    print("\nSummary")
    for model_key in args.models:
        for label in mmlu_labels + [TRIVIAQA[2]]:
            if label in counts[model_key]:
                rate = rates[model_key].get(label)
                suffix = f", sycophancy {rate:.1f}%" if rate is not None else ""
                print(f"  {model_key:12s} {label:12s} "
                      f"n={counts[model_key][label]:5d}{suffix}")


if __name__ == "__main__":
    main()
